
/*import { Geist, Geist_Mono } from "next/font/google";*/
"use client"
import AuthContextProvider from "./context/AuthContextProvider";
import "./globals.css";
import Navbar from "./navbar/page";
import { useRouter } from "next/navigation";
import { DarkModeProvider } from "./darkModeContext/page";

/*const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({ children }) {
  const router = useRouter();

  // Hide navbar only on the landing page ("/")
  const showNavbar = router.pathname !== "/";
  return (
    <html lang="en">
      <body
        /*className={`${geistSans.variable} ${geistMono.variable} antialiased`}*/
      >
        <AuthContextProvider>
          <DarkModeProvider>
            {showNavbar && <Navbar />}
        
            {children}
          </DarkModeProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
